"""users is_allowed

Revision ID: e0a64c15d333
Revises: 69d4c738deb6
Create Date: 2026-06-10 17:31:50.846386

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e0a64c15d333'
down_revision: str | None = '69d4c738deb6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_allowed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_allowed')
    # ### end Alembic commands ###
